### ISSUE TITLE
Disable dimming of text

### ISSUE THREAD

**Issue by jwerts** [teabyii/vscode-ayu#10]
I love this theme - can't find any others I like near as much.  However, the dimming of text in the file list, etc makes it nearly unusable on one of my monitors that's a bit dim.  Is there a way to disable that effect (or lessen) that seems to have been introduced in the last release?

**Comment by pahen** [comment]
It uses the same colors as the original theme for Sublime Text. But if you want to increase the contrast you can try putting this in your settings.json:

For dark theme:
```
"workbench.colorCustomizations": {
    "foreground": "#526375"
}
```

For mirage theme:
```
"workbench.colorCustomizations": {
    "foreground": "#627181"
}
```

**Comment by jwerts** [comment]
Excellent.  Thank you!
