### ISSUE TITLE
Big fan of the theme, but too dark in last release

### ISSUE THREAD

**Issue by quentez** [teabyii/vscode-ayu#11]
I've been a user of this theme since I switched to VSCode, and I'm a big fan. But with the latest release, panels on the left got themed as well and everything is now very very dark (almost unusable).

Here's an example from my extension list:

<img width="517" alt="screen shot 2017-05-19 at 2 59 32 pm" src="https://cloud.githubusercontent.com/assets/504055/26268329/c9680c94-3ca3-11e7-821f-66f34a41cdc5.png">

The contrast for the text is very low, and I'm having trouble reading it (whereas the source code looks great, as usual).

**Comment by teabyii** [comment]
See #10 plz.
It uses the same colors as the original theme for Sublime Text. You can try to customize the colors in your settings.json.
Or you can make suggestion to [ayu](https://github.com/dempfi/ayu). If it updates, I will follow as soon as possible.
