### ISSUE TITLE
Change status bar highlight 

### ISSUE THREAD

**Issue by ajitid** [teabyii/vscode-ayu#13]
Steps to reproduce:
1. Use Ayu Mirage
2. Press Ctrl+M
You'll see green color on status bar, and 'Tab moves focus' is written there, which is barely visible. I think it isn't colored by you. Please provide a color to it for all themes.
3. Press Ctrl+M to turn it off

**Comment by pahen** [comment]
We should use `statusBarItem.prominentBackground` and `statusBarItem.prominentHoverBackground` for this @teabyii

**Comment by pahen** [comment]
And it's Ctrl+Shift+M to set the accessibility mode for me ..

**Comment by ajitid** [comment]
Ah sorry, it would be Ctrl+Shift+M

**Comment by ajitid** [comment]
![capture](https://cloud.githubusercontent.com/assets/26769888/26406740/cc315126-40b6-11e7-9307-827d26168f00.PNG)
I'm using default keybinding so it's Ctrl+M for me.
