### ISSUE TITLE
Add border between file manager and editor

### ISSUE THREAD

**Issue by brhs** [teabyii/vscode-ayu#15]
![screen shot 2017-05-24 at 2 40 31 pm](https://cloud.githubusercontent.com/assets/1924187/26426776/f64b5cd6-408e-11e7-83d5-21ed2386fc6c.png)

There is no border between the file manager and editor. This is visually jarring and unappealing.

**Comment by pahen** [comment]
It will be added really soon since it's been added in the VSCode API recently. See https://github.com/teabyii/vscode-ayu/issues/9

**Comment by pahen** [comment]
See https://github.com/Microsoft/vscode/issues/26530 for more info.
