### ISSUE TITLE
Highlighted buttons in find panel is hard to distinguish

### ISSUE THREAD

**Issue by idiotWu** [teabyii/vscode-ayu#20]
![screenshot](https://user-images.githubusercontent.com/6022672/27508818-919889aa-5928-11e7-999a-41ba07e70c2f.png)

Like the screenshot above, it's hard to tell enabled buttons from disabled ones. I think the disabled button should be a little more darker.

P.S. The status of buttons in screenshot: 1/1/0

**Comment by pahen** [comment]
Fixed and published in v0.6.0
