### ISSUE TITLE
Disable italic in `this`

### ISSUE THREAD

**Issue by Ikderrr** [teabyii/vscode-ayu#21]
Is there any way to disable italic in `this` keyword? I really love this theme and this is the only thing I don't like, so it'd be great if you can show a way to remove this!

**Comment by rafa-acioly** [comment]
I would like to know how to "enable" and "disable", I like the italic in the word "this" and would like to add to the attributes of the html as well.

**Comment by teabyii** [comment]
@Ikderrr I can't find how to set theme configuration in `setting.json`, Maybe you can fork to make a new one, or just modify the theme files in `~/.vscode/extensions/teabyii.ayu-0.4.0/ayu-[which you use].json`, then reload ayu theme.

The setting is here:
```js
{
  "name": "Language methods",
  "scope": "variable.language",
  "settings": {
    "fontStyle": "italic", // remove
    "foreground": "#5CCFE6"
  }
},
```
