### ISSUE TITLE
Allow for tweaking of non-highlight elements

### ISSUE THREAD

**Issue by batjko** [teabyii/vscode-ayu#23]
I really like the Dark version of this theme, as it focuses me on the code and blends out a lot of the distractions from the rest of the editor.

However, a lot of the blended-out bits and bobs (e.g. unedited files in explorer or text in the bottom status bar) are now practically invisible on a lot of my screens, making it very hard to scan for a file or to see some of those details on first glance, without squinting:

![image](https://user-images.githubusercontent.com/7287076/28561808-bb4a543e-7117-11e7-96f6-73264e87344b.png)
![image](https://user-images.githubusercontent.com/7287076/28561845-eae245e4-7117-11e7-82db-6523a5b353da.png)

I was wondering if we could get some configuration options to tweak this, say in this instance to lighten up the low-contrast elements?

**Comment by pahen** [comment]
I agree that the contrast in the dark theme is too low and it's something alot of users has complained about. We have used the same colors as the original sublime text theme so not sure if we should stop doing that or try to get the colors changed in original theme changed first. But here's my suggestion to the new foreground that follows the Web Content Accessibility Guidelines (WCAG) 2.0.

Current:
https://leaverou.github.io/contrast-ratio/#%233e4b59-on-%230f1419

New:
https://leaverou.github.io/contrast-ratio/#%23526375-on-%230f1419

What do you say @teabyii ?

**Comment by dempfi** [comment]
@pahen current is actually this https://leaverou.github.io/contrast-ratio/#%23515C66-on-%230f1419

**Comment by pahen** [comment]
Sweet! Didn't know you already fixed this @demfi. Looks much better! Can you update ayu-colors @k15a so we can rebuild this theme to match the updated colors?

**Comment by k15a** [comment]
Published as version 4. Please ping me if I forget to update the package again :)

**Comment by k15a** [comment]
It seems that `syntax.gutterFg` is now `syntax.gutter` so you might need to update some things :)

**Comment by pahen** [comment]
Awesome! Thanks :)

**Comment by pahen** [comment]
I'm on vacation right now but I'll create a PR as soon as I'm back if not @teabyii already fixed it.

**Comment by pahen** [comment]
PR https://github.com/teabyii/vscode-ayu/pull/24 created now @teabyii :)
