### ISSUE TITLE
[Syntax highlighting, JS] Only certain functions calls are highlighted

### ISSUE THREAD

**Issue by kristianpedersen** [teabyii/vscode-ayu#26]
**I would like all the functions calls in the screenshot to be yellow:**

![ayu](https://user-images.githubusercontent.com/5204369/29998571-fe6f88e8-902e-11e7-9d26-e79187a7384c.png)

In the if statement, I would expect `getBoundingClientRect()` to be yellow, as well as `clearInterval(animasjon)`. I guess `displayPrice()` is coloured because it's a function I've made.

However, I'm also confused as to why `.filter` is yellow, but `.forEach` isn't.

Is there a setting somewhere in a file where I can change this? I tried changing `C:\Users\[username]\.vscode\extensions\teabyii.ayu-0.3.0\ayu-light.json`, but nothing happens, even if I change all the colours in that file.

Thanks for your good work!

**Comment by pahen** [comment]
How does the official vscode themes looks for you? It does the correct thing?

**Comment by kristianpedersen** [comment]
Apologies - I must have had an old version of your theme installed. 

Things look as expected now that I've updated.
