### ISSUE TITLE
Bad vertical alignment of icons in sidebar

### ISSUE THREAD

**Issue by pahen** [teabyii/vscode-ayu#32]
<img width="229" alt="screen shot 2017-09-21 at 08 54 25" src="https://user-images.githubusercontent.com/353888/30682634-a3769992-9eaa-11e7-8d07-8736efbcc65e.png">

We probably need to adjust the size of all the icons to fix this. Also ensure we use the updated icons from https://github.com/dempfi/ayu/tree/master/icons

**Comment by teabyii** [comment]
Close this issue for the [new ayu icon](https://github.com/teabyii/vscode-ayu/pull/49).
