### ISSUE TITLE
Syntax coloring seems to be incomplete

### ISSUE THREAD

**Issue by sveggiani** [teabyii/vscode-ayu#34]
Ayu is my preferred color theme for VSCode but I've noticed that syntax coloring isn't much complete as in another themes. 

Please, note the difference with Oceanic Plus in the following screenshot:

![image](https://user-images.githubusercontent.com/560791/31473924-e4694a70-aecd-11e7-91b5-f156f13ecca6.png)

Is this intended or could the coloring be enhanced?

**Comment by pahen** [comment]
The color theme has not been updated for a very long time and could probably be enhanced a lot. Up for a PR? :)

**Comment by sveggiani** [comment]
@pahen I've never made a theme before, but I'll try :) cc: @teabyii

**Comment by skbolton** [comment]
I am ready and willing to take a crack at this. I feel that this themevis falling too far behind Ayu in sublime

**Comment by SanjayBanjade** [comment]
@sveggiani What's the name of the font you are using in that screenshot?

**Comment by skbolton** [comment]
Wanted to update those that are interested. I have started doing my best to get the color scheme matching ayu on sublime. There are still things missing and I am not sure how it is going to react with other languages but here is a preview of how it is looking.

The image on the left is the same file in sublime
<img width="2117" alt="screen shot 2018-06-22 at 8 50 32 pm" src="https://user-images.githubusercontent.com/13260877/41805003-1e6c717c-765e-11e8-87b1-1acdd1848a79.png">

**Comment by pahen** [comment]
Nice job @skbolton :) Could you provide a screenshot of how that code looks in VSCode without your tweaks too?

**Comment by nscmnto** [comment]
@skbolton looking good so far! I'd love to test it out.

**Comment by skbolton** [comment]
Sorry guys I dropped off there. I also code in elixir and whatever I did broke the highlighting of it pretty bad. I am going to make another run at this and see if I can get it there again while supporting highlighting if other languages as well

**Comment by mrtkrcm** [comment]
would love to see full syntax support for JS with Ayu Dark 🤩

**Comment by skbolton** [comment]
@mrtkrcm the bottom photo in my post above is the dark version

**Comment by mrtkrcm** [comment]
Do you have that somewhere already? or can you push your changes to somewhere as a PR or updated fork?

**Comment by skbolton** [comment]
@mrtkrcm I will put some work into it this weekend and post an update/pr here in the repo. The first pass will be updating the color palette. After that I might tackle customizing the ui separation lines and what not

**Comment by pahen** [comment]
Just wanted to let you know that work on this has already been started by the author of the original Sublime Text theme. See https://github.com/teabyii/vscode-ayu/pull/60

**Comment by skbolton** [comment]
oh nice well lets close this issue then!

**Comment by pahen** [comment]
Closing in favour of https://github.com/teabyii/vscode-ayu/pull/60
