### ISSUE TITLE
Hide Explorer Arrows

### ISSUE THREAD

**Issue by atomi** [teabyii/vscode-ayu#35]
Can we add: 

           "hidesExplorerArrows":true 

 https://code.visualstudio.com/updates/v1_18#_folder-icons-in-file-icon-themes

Also a *.qtpl definition would be nice.

**Comment by smlombardi** [comment]
I modified my copy of your theme to do this and, IMO, it looks great:

<img width="289" alt="screen shot 2017-11-10 at 2 10 42 pm" src="https://user-images.githubusercontent.com/835148/32674401-1f2ec350-c621-11e7-8eb8-64f1e8e6456f.png">

**Comment by atomi** [comment]
Yeah it does. I hope it gets merged.

**Comment by pahen** [comment]
Included in the v0.9.0 release :)

**Comment by rawkode** [comment]
Eurgh, not a fan. Please make this toggle-able
