### ISSUE TITLE
Wrong color for plain text and dots in Ayu-mirage

### ISSUE THREAD

**Issue by theobroma** [teabyii/vscode-ayu#37]
I fell in love with ayu-mirage from Sublime Text. Now I gave him a break and trying to use VS Code.
I was pleasantly surprised that my favourite theme ported to VS Code. But there is a problem: some elements are not correctly highlighted. On screenshots everything fine except the third one.
![vscode-ayu-dark-withtext](https://user-images.githubusercontent.com/4540573/32624528-333a105a-c592-11e7-920c-5def9ad7452b.jpg)
![st3-ayu-mirage-withtext](https://user-images.githubusercontent.com/4540573/32624527-3314b1de-c592-11e7-86bd-b313bd1cf926.jpg)
![vscode-ayu-mirage-withtext](https://user-images.githubusercontent.com/4540573/32624529-3361639e-c592-11e7-926d-408894fcd281.jpg)
We can see, that Ayu-dark detects elements correctly, so it's reasonably to expect the same behavior from Ayu-mirage.
**VS Code version of Ayu-mirage definitely should look like it's SublimeText version!**
How can I achive this goal?

**Comment by pahen** [comment]
This is now fixed in v0.10.0
