### ISSUE TITLE
VSCode ayu light + long commit message = invisible text

### ISSUE THREAD

**Issue by isidorn** [teabyii/vscode-ayu#4]
1. VSCode insiders, ayu light theme
2. Git viewlet, type a long text in the git commit box
3. Text becomes invisible (git tries to render the text red due to commit mesage being too long)

fyi @aeschli

![screen shot 2017-02-08 at 16 55 28](https://cloud.githubusercontent.com/assets/1926584/22745051/8b244808-ee1f-11e6-9d65-5b630080242d.png)

**Comment by teabyii** [comment]
I can not make it happen in vscode 1.10.2 in Mac.

**Comment by teabyii** [comment]
The theme of this part seems not to be controlled by `.tmTheme`.

**Comment by isidorn** [comment]
I also stopped seeing this in latest vscode now
