### ISSUE TITLE
Inconsistent method highlighting.

### ISSUE THREAD

**Issue by TeeSeal** [teabyii/vscode-ayu#42]
I've noticed that when typing out methods, some will get highlighted and some won't:

![image](https://user-images.githubusercontent.com/14080148/34342143-d013ee6e-e9af-11e7-9359-e3520bf00c92.png)

![image](https://user-images.githubusercontent.com/14080148/34342157-fe996c28-e9af-11e7-9a2e-d21d48478b3d.png)

Notice how the `post` is colored while the `get` is not. I don't know if this is intended, but I'd rather have all my methods in the colored format.

**Comment by pahen** [comment]
What language is this in? I tried Javascript and it works as expected there.

**Comment by TeeSeal** [comment]
That is javascript 🤔

**Comment by pahen** [comment]
I can't reproduce this. Is it working for you when you're using other themes? What version of VSCode are you using? And what version of Ayu theme?

**Comment by sveggiani** [comment]
I can reproduce this. By inspecting the sytax scopes we can see that "get" is not being detected as a function.

![imagen](https://user-images.githubusercontent.com/560791/34563857-2ebab15c-f133-11e7-9545-c917432b4020.png)

![imagen](https://user-images.githubusercontent.com/560791/34563901-4f170a04-f133-11e7-90c9-5e8294e57d0a.png)

My first tought was that this could be related with the length of the function/method name, but if you try 2 characters it gets colored correctly.

Seems to be related to the "get" name to me.

**Comment by pahen** [comment]
Thanks for the info @sveggiani. It detect it as a function for me though.

<img width="463" alt="screen shot 2018-01-04 at 14 15 55" src="https://user-images.githubusercontent.com/353888/34565156-03591bb2-f15a-11e7-9d6a-4cad3c85a6b0.png">

What version of VSCode and which extensions are you using?

**Comment by TeeSeal** [comment]
**VSCode** 1.19.1
**Ayu**: 0.11.1

**Other extensions:**
- Align 0.2.0
- Bookmarks 0.18.0
- ElixirLS 0.2.9
- ESLint 1.4.3
- file-icons 1.0.7
- Git Lens 7.2.0
- Prettier 1.0.1
- Ruby 0.15.0
- TSLint 1.0.24
- Vetur 0.11.4

And yeah, it works with other themes (not all), Dark+ for example:
![image](https://user-images.githubusercontent.com/14080148/34568342-2749d2fa-f16e-11e7-899c-752dcb5f2253.png)

But they still are detected as different types:
![image](https://user-images.githubusercontent.com/14080148/34568382-537f9b52-f16e-11e7-8167-8da6714ebeb1.png)
![image](https://user-images.githubusercontent.com/14080148/34568392-5c1cb7c2-f16e-11e7-9710-b4d481236c8b.png)

So I guess this is partially VSCode's fault.

@pahen can I know what you're using to have them detect properly?

**Comment by TeeSeal** [comment]
Maybe it would be a good idea to have coloring for the `support.function` scope?

I'm facing the same issue with ruby, except it's worse:
![image](https://user-images.githubusercontent.com/14080148/34568579-f0b9f3ea-f16e-11e7-9470-cb95e90cab57.png)

The words in yellow are detected as `entity.name.function` and the ones in white as `support.function`, making my statements look like zebras.

**Comment by TeeSeal** [comment]
I changed one of the rules in the source code of the package by adding `support.function` to the scope:
```js
    {
      "name": "Function, Special Method, Block Level",
      "scope":
        "support.function, entity.name.function, keyword.other.special-method, meta.block-level",
      "settings": {
        "foreground": "#FFD580"
      }
    }
```
Which seems to have fixed my issue, now it looks exactly like I want it to:
![image](https://user-images.githubusercontent.com/14080148/34569112-69912ee0-f170-11e7-9a21-c0992f4bd984.png)
![image](https://user-images.githubusercontent.com/14080148/34569087-5c1e036e-f170-11e7-8e2c-f62af0c41316.png)

Guess I'll stick with this patch for now. I'm going to close this issue. Let me know if you want me to PR these change @pahen .

**Comment by pahen** [comment]
It could be the extension https://github.com/dzannotti/vscode-babel that solves the issue for me. But I'm up for a PR to fix it for users like you :)

**Comment by pahen** [comment]
Thanks for the help! Added in v0.11.2 of the theme
