### ISSUE TITLE
[Questions] What is the font used in the screenshot?

### ISSUE THREAD

**Issue by Gal3riel** [teabyii/vscode-ayu#48]
Hi all, I am very interested in the font used in the screenshot, could someone please tell me the name of it?

**Comment by pahen** [comment]
Which one of the screenshots are you referring to?

**Comment by pahen** [comment]
It’s called Operator Mono

**Comment by rahilwazir** [comment]
Hmm, not sure if the screenshot was updated but the fonts in the screenshot don't look Operator Mono to me? What variant are you using if its Operator Mono?

**Comment by dempfi** [comment]
@rahilwazir yep, the current screenshots show the theme with PragmataPro.
