### ISSUE TITLE
Ayu Light + TOML. Line is invisible when no value set

### ISSUE THREAD

**Issue by rpeshkov** [teabyii/vscode-ayu#53]
Screenshot:
![screen shot 2018-03-08 at 23 27 05](https://user-images.githubusercontent.com/701068/37180133-3c2e5b6e-2328-11e8-93d7-258b71d6914a.png)

Same strings, but with selection:
![screen shot 2018-03-08 at 23 27 35](https://user-images.githubusercontent.com/701068/37180155-53a5d6aa-2328-11e8-994e-79bc6920503c.png)

**Comment by dempfi** [comment]
Fixed in #60. Errors now are shown in red.

**Comment by rpeshkov** [comment]
@dempfi thanks!
