### ISSUE TITLE
How about adding a light version with a mix of solarized colors?

### ISSUE THREAD

**Issue by THPubs** [teabyii/vscode-ayu#56]
Just did some modifications and added solarized background colors. Let me what you think. If good I can make a pr 😄 

<img width="1518" alt="screen shot 2018-04-12 at 6 23 24 am" src="https://user-images.githubusercontent.com/1212023/38650567-405d9bde-3e1a-11e8-9505-75be3c89c7c7.png">

**Comment by teabyii** [comment]
Thank you very much. However, I am very sorry that I can't make decisions on this, a new version of theme color, I keep my best to follow [Ayu](https://github.com/dempfi/ayu). So, please issue for [Ayu](https://github.com/dempfi/ayu).

**Comment by THPubs** [comment]
Ah no issue! I understand.
