### ISSUE TITLE
Most Recent update changed theme colors

### ISSUE THREAD

**Issue by M-Porter** [teabyii/vscode-ayu#61]
It seems as though magenta/purple has been completely removed in favor of yellow, orange and a rustic red (which has 0 contrast difference to orange). It also seems as though the contrast has been greatly decreased making it much harder to see gutters and separators.

## New TS
![image](https://user-images.githubusercontent.com/2313263/44281659-5e968f00-a20d-11e8-8b8b-b94b002ae473.png)

## Old TS
![image](https://user-images.githubusercontent.com/2313263/44281666-66563380-a20d-11e8-85ca-c4fca2fbd056.png)

If all of this is intentional fine... but ayu went from being beautifully colored to a dull mess of low contrast reds, yellows, oranges and white. The README should be updated to include screenshots of the new theme. 

Also, the updates look even worse in other languages (php/go).

**Comment by joshtynjala** [comment]
I definitely miss that purple/violet color. Please bring it back!

Additionally, I hate that the status bar now changes to an orange/coral color during debugging. The high contrast is very distracting, and it contradicts the following line from the changelog:

> Update UI colors to reduce contrast, and improve focus on editor

**Comment by batjko** [comment]
I code mostly in Javascript and have used Ayu dark for a long time now.
Every now and then I look at other themes but always decide not to switch, because the syntax colors were just the most beautiful I can find.

The recent change introduced this dull grey for standard tokens for some reason, and `require` is now weirdly red and it all just annoys me now.

I really hope this was a mistake and it's going back soon. 🙏

**Comment by blakeperdue** [comment]
I also noticed that the borders around tabs and around the top and bottom bars in VS Code have been removed. Was this intentional? It is much harder to visually separate those different parts of the interface now:

![image](https://user-images.githubusercontent.com/1642071/44302315-e9ea5000-a2f3-11e8-9a19-1ef2ac77b700.png)

**Comment by blakeperdue** [comment]
imho, the old UI with the light borders looked better:
![image](https://user-images.githubusercontent.com/1642071/44302322-09817880-a2f4-11e8-8a22-8ce49b1b98d1.png)

**Comment by balajmarius** [comment]
Managed to add back some of the missing borders on `Ayu-Mirage` using the following config:

```json
  "workbench.colorCustomizations": {
    "contrastBorder": "#373f4a",
    "tab.border": "#373f4a",
    "sideBar.border": "#373f4a",
    "titleBar.border": "#373f4a",
    "statusBar.border": "#373f4a",
    "activityBar.border": "#373f4a",
    "editorRuler.foreground": "#373f4a",
    "editorGroupHeader.tabsBorder": "#373f4a",
    "editorOverviewRuler.border": "#373f4a"
  }
```

**Comment by M-Porter** [comment]
@balajmarius `#39424E` is the color for the gutter as defined at https://github.com/ayu-theme/ayu-colors if you feel like being _super_ particular about it

**Comment by M-Porter** [comment]
Unfortunately (to those of us in this thread), it seems as though the new updates actually make the colors fall in line with the official Ayu sublime theme

![image](https://user-images.githubusercontent.com/2313263/44358600-5be4a580-a46a-11e8-8764-092accb81ee4.png)

If that is the case then not much can be done about it as that theme is the source of truth.

**Comment by alexsasharegan** [comment]
Is anyone else having trouble with the selection areas not being very visible? I often rely on the selection showing me other usages, and they just don't light up strongly or even consistently.

Here's an example where I have `hits` selected. The selection and the usage below are dim, while above is bright and what I would prefer consistently.

![image](https://user-images.githubusercontent.com/16269252/44362850-2abea200-a477-11e8-8d19-be7a28d15d55.png)

**Comment by batjko** [comment]
@alexsasharegan I think that's already logged under https://github.com/teabyii/vscode-ayu/issues/22

**Comment by alexsasharegan** [comment]
@batjko , I've moved my comment to #22. Thanks for pointing me in the right direction!

**Comment by dempfi** [comment]
Hey guys, I hear what you are saying and I promise to think on balancing the colours in the theme (function arguments need different colour, that's given). Some other stuff like removal of some borders aren't final and might change too. Anyhoo, thank you all for the feedback 🤗

**Comment by alexsasharegan** [comment]
Great work on this theme! It's my main stay for sure! Thanks for taking the feedback into consideration!

**Comment by blakeperdue** [comment]
+1 on the work on this theme, I certainly appreciate it. 

@M-Porter or @balajmarius do you have the `colorCustomizations` names to bring back some of the old magenta/purple colors for more contrast? For now, I manually reverted back to 0.14.0: https://github.com/blakeperdue/vscode-ayu

**Comment by alexsasharegan** [comment]
As a side note, if you're trying to customize some of these colors and you've ever used material design themes, they make some global adjustments to your selection colors.

**Comment by M-Porter** [comment]
@blakeperdue i haven't had the time to look into it. been crazy busy the past few days. if i do get around to it i'll make sure to create a gist and post it here

**Comment by dempfi** [comment]
Arguments colours are fixed in #62. It would be cool if you guys would be able to test it.

**Comment by alexsasharegan** [comment]
How would we test it? Just dump the settings into our settings under `"[Ayu Dark]"`?

**Comment by blakeperdue** [comment]
@alexsasharegan You can clone that repo and manually [copy the repo](https://github.com/ayu-theme/vscode-ayu/tree/function-arguments-colors) into your extensions folder (`~/.vscode` on mac).

@dempfi Looks like your PR works, commented on it at #62 .

**Comment by alexsasharegan** [comment]
Looks like it's the same for linux. I'll give this a go!

**Comment by funct7** [comment]
<img width="1091" alt="screen shot 2018-08-27 at 1 57 46 pm" src="https://user-images.githubusercontent.com/12147008/44641352-7803bc00-aa01-11e8-8e8c-478945b03fea.png">
<img width="1060" alt="screen shot 2018-08-27 at 1 57 52 pm" src="https://user-images.githubusercontent.com/12147008/44641353-7803bc00-aa01-11e8-82a9-02666969a87c.png">

The new color scheme is **NOT** ayu at all.

**Comment by dempfi** [comment]
OK guys, fix for functions args colours have been released.

@funct7 yeah, markdown-related colours are a "bit" off. Preparing a fix now.

**Comment by saifahn** [comment]
I didn't see much positive feedback for the recent changes, so I just wanted to say that I actually do like the colours being closer to the Sublime theme.

**Comment by dempfi** [comment]
FYI guys, I'm still fine-tuning an update to improve overall experience of the theme and address your feedback (indirectly). There are still few things for me to work on but otherwise it's really close to being ready.

@saifahn thx 🤗

**Comment by dempfi** [comment]
Hey guys, I'm sorry for delay in response — it took me a while to find time to polish and extensively test updates. 

Anyhoo, WIP PR is here https://github.com/teabyii/vscode-ayu/pull/70 and I welcome all you to give it a shot.

--- 
Steps to install it:
- Download bundled theme [from here](https://github.com/teabyii/vscode-ayu/blob/e406f9aa17473019985625adc09947c673111a7d/ayu-0.16.0.vsix);
- In your VSCode open command palette (<kbd>Shift</kbd> + <kbd>Cmd</kbd> + <kbd>P</kbd> on macOS) ;
- Type "install from VSIX" and select downloaded bundle;
- Reload the window;

**Comment by pahen** [comment]
I really like your latest changes @dempfi. Awesome work as always :) Time to make this theme official and maintained by you maybe? ;)

**Comment by dempfi** [comment]
@pahen I'm glad you liked it. This repo probably can be moved to the [ayu-theme](https://github.com/ayu-theme), tho I believe such decision should be made by @teabyii.

**Comment by teabyii** [comment]
I feel OK to move it to the [ayu-theme](https://github.com/ayu-theme). @dempfi Please remove the fork in ayu-theme, and I will do it.

**Comment by dempfi** [comment]
@teabyii done :)

**Comment by teabyii** [comment]
@dempfi I have no permission to create repositories on [ayu-theme](https://github.com/ayu-theme).

**Comment by M-Porter** [comment]
Thanks for the updates @dempfi ! Looks great now. Closing as i feel my initial comments have been well address and solved

**Comment by pouryax7x** [comment]
I had a problem with color of "editorSuggestWidget.selectedBackground" ...
I was really confused as to which option was chosen when i have two or three number of suggestion as u can see in first picture .

<img width="455" alt="aa" src="https://user-images.githubusercontent.com/18659000/85951754-6cc1a480-b97a-11ea-88a2-d0a8d82e145a.png">


so i decide to change color with : 
`"workbench.colorCustomizations": {
    "editorSuggestWidget.selectedBackground": "#18495e"
  }`
in my "**setting.js**"

as u can see in 2nd pic 👍

<img width="464" alt="2" src="https://user-images.githubusercontent.com/18659000/85951762-777c3980-b97a-11ea-855b-661c11baa5f1.png">

i suggest to change it color in next update . thank you.
