### ISSUE TITLE
Adopt workbench themes

### ISSUE THREAD

**Issue by joaomoreno** [teabyii/vscode-ayu#7]
Hey, VS Code dev here. I love these themes!

[VS Code Workbench theming](https://code.visualstudio.com/updates/v1_11#_preview-workbench-theming) is now in preview, but we can already start using it. I would love to get these themes working across the whole workbench.

Let me know if you'll accept a PR.

**Comment by pahen** [comment]
I've started adding custom theme colors for the entire workbench for the Ayu Dark theme. Let me know if you're interested in a PR! Note that it's a work in progress.

<img width="1087" alt="screen shot 2017-05-04 at 09 59 18" src="https://cloud.githubusercontent.com/assets/353888/25694756/64c2d03e-30b0-11e7-9103-e8789e9c07dd.png">

**Comment by joaomoreno** [comment]
Looks great, although the lack of contrast between the background of the different parts is kind of strange.

**Comment by pahen** [comment]
Yes, I agree. But the goal is to have it as close as the original Sublime Text theme as possible. But there's still elements that can't be themed to achieve that now. Mostly lack of border theming. And this issue https://github.com/Microsoft/vscode/issues/25774 created by me.

**Comment by Michael-ABOSS** [comment]
Awesome! was checking if this would be added. Good to see you are already working on it!

**Comment by teabyii** [comment]
Nice, you are welcome. @pahen

**Comment by pahen** [comment]
Here's a gist if someone want to test it: https://gist.github.com/pahen/d435d91d21c7b3556c156e5618b7dd3d

Just put it in your settings. I'll create a PR once the theming API in vscode is satisfying enough :)

**Comment by pahen** [comment]
I'm making progress on all 3 versions (light, mirage, and dark). Screenshots coming soon! :)

**Comment by Michael-ABOSS** [comment]
I have been using the Dark theme you posted in the gist for the last two days. Looking very good have not run in to any bugs. Will also test the other versions when you are ready

**Comment by joaomoreno** [comment]
Pretty cool. I'd love to get some contrast between the sidebar and the editor, even if only a slight dim border.

**Comment by pahen** [comment]
https://github.com/teabyii/vscode-ayu/pull/8
